
### Add a new plant
POST http://localhost:5000/plants
Content-Type: application/json

{
    "name": "tulasi",
    "type of plant": "Succulent",
    "category": "Medicinal"
}

###route to get all plants
GET http://localhost:5000/plants/all
Content-Type: application/json

###Route to get a plant by name
GET http://localhost:5000/plants/<string:name>
Content-Type: application/json

###route to update  a plant by plant_id
PUT http://localhost:5000/plants/<int:plant_id>
Content-Type: application/json

{
    "name": "Tulasi",
    "type of plant": "Succulent",
    "category": "Medicinal"
}

###route to delete  a plant by id
DELETE http://localhost:5000/plants/<int:id>
Content-Type: application/json