POST http://127.0.0.1:5000/tasks
Content-Type: application/json

{
     "id": 4,
     "task": "loops in python",
     "status": " completed"
}

### Get all tasks
GET http://127.0.0.1:5000/tasks
Accept: application/json

### Get specific task by ID
GET http://127.0.0.1:5000/tasks?id=2
Content-Type: application/json

### PUT request(Updating a task's status whether completed or not)
PUT http://localhost:5000/tasks/5
Content-Type: application/json

{
    "id": 4
    
}

### Delete a task by ID
DELETE http://127.0.0.1:5000/tasks/4

Content-Type: application/json









